"""
Exercise Catalog Seed Data with comprehensive details:
- Name
- Category (Chest, Back, Shoulders, Biceps, Triceps, Legs, Core, Abs)
- Target Muscle Group
- Equipment (Barbell, Dumbbell, Cable, Machine, Bodyweight)
- Difficulty (Beginner, Intermediate, Advanced)
- Description
- Instructions
- Default Sets (int)
- Default Reps (int)
- Recommended Sets (str, e.g. "3-4 sets")
- Recommended Reps (str, e.g. "8-12 reps")
- Common Mistakes (str)
- Rest Seconds (int)
- YouTube Video ID & Full URL
"""

EXERCISE_CATALOG = [
    # ================= CHEST =================
    {
        "name": "Barbell Bench Press",
        "category": "Chest",
        "muscle_group": "Pectoralis Major (Mid & Lower Chest), Anterior Deltoid, Triceps",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "The fundamental compound barbell movement for maximal upper-body pushing power, chest thickness, and mechanical loading.",
        "instructions": "Lie flat on the bench with eyes directly below the bar. Grip slightly wider than shoulder width. Retract scapulae and plant feet firmly. Lower the bar with control to lower sternum, flare elbows ~45-75 degrees, press explosively through the palms to lockout.",
        "default_sets": 4,
        "default_reps": 8,
        "recommended_sets": "3-5 sets",
        "recommended_reps": "6-10 reps (Strength / Hypertrophy)",
        "common_mistakes": "Bouncing the bar off the ribcage, flaring elbows out to 90 degrees (straining rotator cuff), lifting buttocks off the bench.",
        "rest_seconds": 90,
        "youtube_id": "rT7DgCr-3pg",
        "youtube_url": "https://www.youtube.com/watch?v=rT7DgCr-3pg"
    },
    {
        "name": "Incline Bench Press",
        "category": "Chest",
        "muscle_group": "Clavicular Pectoral Head (Upper Chest), Anterior Deltoids, Triceps",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Evidence-based compound barbell movement emphasizing clavicular head hypertrophy and upper chest fullness.",
        "instructions": "Set bench to 30 degrees. Unrack barbell over upper chest. Lower smoothly to upper sternum just below clavicles while keeping shoulder blades pinched back. Drive upward back over eyes.",
        "default_sets": 4,
        "default_reps": 8,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "6-10 reps",
        "common_mistakes": "Incline angle too steep (>45 degrees shifts work to front delts), elbows flared 90 degrees, bouncing off the chest.",
        "rest_seconds": 90,
        "youtube_id": "2yjwXTZQDDI",
        "youtube_url": "https://www.youtube.com/watch?v=2yjwXTZQDDI"
    },
    {
        "name": "Incline Dumbbell Press",
        "category": "Chest",
        "muscle_group": "Clavicular Pectoral Head (Upper Chest), Front Delts, Triceps",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Premier upper-chest builder offering convergent pressing arcs and deep stretch without wrist impingement.",
        "instructions": "Set adjustable bench between 30 and 45 degrees. Kick dumbbells up to shoulder level. Press dumbbells up and slightly inward over upper chest while keeping shoulder blades pinched back.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Setting bench angle too high (>45 degrees shifts load to anterior delts), colliding dumbbells together at top which loses tension.",
        "rest_seconds": 90,
        "youtube_id": "8iPEnn-ltC8",
        "youtube_url": "https://www.youtube.com/watch?v=8iPEnn-ltC8"
    },
    {
        "name": "Cable Chest Fly",
        "category": "Chest",
        "muscle_group": "Sternal Pectoralis Major, Inner Chest Cleavage",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Continuous tension isolation exercise delivering maximum horizontal adduction contraction across the sternal chest fibers.",
        "instructions": "Set pulleys at chest height. Take one step forward in a staggered stance. Keep a slight, fixed bend in elbows and bring handles together in an expansive hugging motion. Squeeze hard at peak adduction.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "10-15 reps (Hypertrophy / Pump)",
        "common_mistakes": "Bending and straightening elbows like a press, allowing shoulders to roll forward at full stretch.",
        "rest_seconds": 60,
        "youtube_id": "Iwe6AmxVf7o",
        "youtube_url": "https://www.youtube.com/watch?v=Iwe6AmxVf7o"
    },
    {
        "name": "Chest Dips",
        "category": "Chest",
        "muscle_group": "Lower Pectoralis Major (Costal Head), Triceps, Anterior Deltoids",
        "equipment": "Bodyweight",
        "difficulty": "Advanced",
        "description": "Calisthenic power movement targeting the lower chest sweep and demanding shoulder girdle stabilization.",
        "instructions": "Mount parallel bars. Lean torso forward ~30 degrees and tuck chin. Lower body smoothly until shoulders are below elbows, then press up contracting lower pecs.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Staying completely upright (shifts load to triceps), dipping too deep without shoulder mobility causing anterior shoulder impingement.",
        "rest_seconds": 90,
        "youtube_id": "2z8JmcrW-As",
        "youtube_url": "https://www.youtube.com/watch?v=2z8JmcrW-As"
    },
    {
        "name": "Push-Ups",
        "category": "Chest",
        "muscle_group": "Pectoralis Major, Triceps, Anterior Deltoids, Core",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Fundamental closed-kinetic-chain horizontal press conditioning chest, serratus anterior, and abdominal core integrity.",
        "instructions": "Place hands slightly wider than shoulders. Maintain straight plank line from heels to crown. Lower chest until 1 inch off the floor, keeping elbows at a 45-degree angle to torso, press back up.",
        "default_sets": 3,
        "default_reps": 15,
        "recommended_sets": "3 sets",
        "recommended_reps": "15-25 reps (or to failure)",
        "common_mistakes": "Sagging hips (lumbar extension), hiking hips in air, flaring elbows out 90 degrees.",
        "rest_seconds": 60,
        "youtube_id": "IODxDxX7oi4",
        "youtube_url": "https://www.youtube.com/watch?v=IODxDxX7oi4"
    },

    # ================= BACK =================
    {
        "name": "Barbell Deadlift",
        "category": "Back",
        "muscle_group": "Erector Spinae, Latissimus Dorsi, Glutes, Hamstrings, Trapezius",
        "equipment": "Barbell",
        "difficulty": "Advanced",
        "description": "The king of posterior chain compound movements, building unparalleled spinal erector density, overall back thickness, and raw hip power.",
        "instructions": "Stand with feet hip-width under bar (bar over midfoot). Hinge at hips to grip bar. Pull slack out of the bar, lock lats down, wedge hips into position. Drive floor away through heels, locking out hips and knees simultaneously.",
        "default_sets": 4,
        "default_reps": 5,
        "recommended_sets": "3-5 sets",
        "recommended_reps": "4-6 reps (Strength / Mechanical Tension)",
        "common_mistakes": "Rounding the lumbar spine, jerking the bar off the floor, hyperextending lower back at lockout.",
        "rest_seconds": 150,
        "youtube_id": "op9kVnSso6Q",
        "youtube_url": "https://www.youtube.com/watch?v=op9kVnSso6Q"
    },
    {
        "name": "Romanian Deadlift (RDL)",
        "category": "Back",
        "muscle_group": "Hamstrings, Gluteus Maximus, Erector Spinae, Latissimus Dorsi",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Hip-hinge posterior chain developer producing extreme eccentric hamstring stretch and mid-lower back stabilization.",
        "instructions": "Hold bar at hips with an overhand grip. Soften knees and push hips straight backward as if touching a wall behind you. Lower bar along shins until hamstrings are fully loaded, then squeeze glutes to return upright.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Squatting down instead of hip-hinging back, letting the barbell drift away from shins, rounding the lower back.",
        "rest_seconds": 90,
        "youtube_id": "_oyxCn2iSjU",
        "youtube_url": "https://www.youtube.com/watch?v=_oyxCn2iSjU"
    },
    {
        "name": "Pull-Ups",
        "category": "Back",
        "muscle_group": "Latissimus Dorsi (V-Taper Width), Teres Major, Biceps Brachii",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Gold standard vertical pulling movement for developing lateral back width and upper-body relative strength.",
        "instructions": "Grip overhead pull-up bar with overhand grip wider than shoulders. Depress scapulae, pull elbows down toward hips until chin clears bar. Lower under control to a dead hang stretch.",
        "default_sets": 3,
        "default_reps": 8,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "6-10 reps",
        "common_mistakes": "Kipping with legs, half reps failing to achieve full elbow extension at bottom, shrugging shoulders to ears.",
        "rest_seconds": 90,
        "youtube_id": "eGo4IYlbE5g",
        "youtube_url": "https://www.youtube.com/watch?v=eGo4IYlbE5g"
    },
    {
        "name": "Bent-Over Barbell Row",
        "category": "Back",
        "muscle_group": "Latissimus Dorsi, Rhomboids, Middle Trapezius, Posterior Delts",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Essential horizontal rowing exercise for creating mid-back 3D density, rhomboid thickness, and upper back strength.",
        "instructions": "Hinge at hips to ~45 degrees with flat back. Grip barbell overhand. Pull bar smoothly toward upper belly button/sternum, driving elbows back. Squeeze shoulder blades together for 1s, lower under control.",
        "default_sets": 4,
        "default_reps": 8,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "6-10 reps",
        "common_mistakes": "Using hip heave/momentum to swing bar up, standing too upright (turning into shrugs), rounding cervical spine.",
        "rest_seconds": 90,
        "youtube_id": "FWJR5Ve8gkQ",
        "youtube_url": "https://www.youtube.com/watch?v=FWJR5Ve8gkQ"
    },
    {
        "name": "Lat Pulldown",
        "category": "Back",
        "muscle_group": "Latissimus Dorsi, Teres Major, Biceps, Lower Trapezius",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Scalable vertical pulling exercise that allows precision isolation of lat fibers through complete range of motion.",
        "instructions": "Secure thighs firmly under pads. Grip wide curved bar with overhand grip. Lean back slightly (~10-15 degrees), drive elbows down into back pockets until bar grazes upper chest, slowly return.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Swinging torso excessively backward, pulling bar behind neck (rotator cuff hazard), pulling with wrists/forearms instead of elbows.",
        "rest_seconds": 75,
        "youtube_id": "CAwf7n6Luuc",
        "youtube_url": "https://www.youtube.com/watch?v=CAwf7n6Luuc"
    },
    {
        "name": "Seated Cable Row",
        "category": "Back",
        "muscle_group": "Mid-Back, Rhomboids, Lower Lats, Erector Spinae",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Horizontal cable pull with continuous tension for sculpting deep rhomboid and mid-trapezius detail.",
        "instructions": "Sit with feet on footplates, knees slightly bent. Grasp V-grip handle, sit tall with chest puffed out. Pull handle into lower abdomen while pinning shoulder blades back, return smoothly.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Excessive rocking forward and back at hips, hunching upper back at peak contraction.",
        "rest_seconds": 75,
        "youtube_id": "GZbfZ033fBQ",
        "youtube_url": "https://www.youtube.com/watch?v=GZbfZ033fBQ"
    },

    # ================= SHOULDERS =================
    {
        "name": "Overhead Barbell Press (Shoulder Press)",
        "category": "Shoulders",
        "muscle_group": "Anterior Deltoid, Lateral Deltoid, Triceps, Upper Chest, Core",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "The quintessential vertical pressing compound movement establishing massive shoulder boulder width and overhead lockout power.",
        "instructions": "Stand with feet shoulder-width, bar resting across clavicles. Squeeze glutes and brace core. Press bar vertically in a straight path, moving head slightly back then pressing head through the window at top lockout.",
        "default_sets": 3,
        "default_reps": 8,
        "recommended_sets": "3-5 sets",
        "recommended_reps": "6-10 reps",
        "common_mistakes": "Arching lower back excessively (compensating for tight lats/shoulders), pressing bar forward in a curved loop, loose core.",
        "rest_seconds": 90,
        "youtube_id": "_RlRDNDowfY",
        "youtube_url": "https://www.youtube.com/watch?v=_RlRDNDowfY"
    },
    {
        "name": "Dumbbell Shoulder Press",
        "category": "Shoulders",
        "muscle_group": "Anterior Deltoid, Lateral Deltoid, Triceps",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Foundational vertical pressing exercise with dumbbells allowing natural humeral path and balanced bilateral overhead strength.",
        "instructions": "Sit upright with back supported. Hold dumbbells at shoulder level with elbows at roughly 75 degrees. Press upward in a controlled arc until arms are extended overhead without clanking bells. Lower with control to chin level.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Arching lower back excessively off the back pad, flaring elbows 90 degrees out, bouncing dumbbells at bottom.",
        "rest_seconds": 90,
        "youtube_id": "qEwKCR5JCog",
        "youtube_url": "https://www.youtube.com/watch?v=qEwKCR5JCog"
    },
    {
        "name": "Arnold Press",
        "category": "Shoulders",
        "muscle_group": "Anterior Deltoid, Lateral Deltoid, Triceps, Rotator Cuff",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Rotational dumbbell overhead press pioneered by Arnold Schwarzenegger to recruit all three deltoid heads through an extended arc.",
        "instructions": "Sit upright holding dumbbells at chin height with palms facing you. As you press upward, rotate wrists outwards so palms face forward at the top lockout. Reverse smoothly on the descent.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Rotating too quickly before pressing, banging dumbbells together overhead, arching lower back.",
        "rest_seconds": 90,
        "youtube_id": "6ZZ133867KQ",
        "youtube_url": "https://www.youtube.com/watch?v=6ZZ133867KQ"
    },
    {
        "name": "Dumbbell Lateral Raise",
        "category": "Shoulders",
        "muscle_group": "Lateral Deltoid (Side Delt / V-Taper Width)",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "The absolute #1 exercise for building wide, capped lateral deltoid heads and creating the illusion of a smaller waistline.",
        "instructions": "Stand with dumbbells at sides, slight hinge forward at hips. With elbows soft, raise dumbbells out to the sides leading with elbows until arms are parallel to the floor. Pour water cue with pinkies slightly higher.",
        "default_sets": 4,
        "default_reps": 12,
        "recommended_sets": "3-5 sets",
        "recommended_reps": "12-15 reps (Strict Hypertrophy)",
        "common_mistakes": "Swinging body / using momentum from legs, shrugging traps up to neck, raising hands above elbows.",
        "rest_seconds": 60,
        "youtube_id": "PzsMitRSR_0",
        "youtube_url": "https://www.youtube.com/watch?v=PzsMitRSR_0"
    },
    {
        "name": "Face Pulls",
        "category": "Shoulders",
        "muscle_group": "Posterior Deltoid, Infraspinatus, Teres Minor, Rhomboids",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Essential shoulder longevity and posture exercise that simultaneously develops the rear delts and external rotator cuff.",
        "instructions": "Attach rope to pulley at eye level. Grip rope with thumbs pointing backward. Step back, pull rope directly toward forehead while separating hands and externally rotating wrists backwards. Hold 1s squeeze.",
        "default_sets": 3,
        "default_reps": 15,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "12-18 reps",
        "common_mistakes": "Using too heavy weight and turning it into a body-row, failing to externally rotate wrists, pulling toward chest instead of eye level.",
        "rest_seconds": 60,
        "youtube_id": "rep-qVOkqgk",
        "youtube_url": "https://www.youtube.com/watch?v=rep-qVOkqgk"
    },
    {
        "name": "Dumbbell Rear Delt Fly",
        "category": "Shoulders",
        "muscle_group": "Posterior Deltoid, Mid-Trapezius",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Targeted rear deltoid isolation eliminating anterior shoulder dominance and rounding posture.",
        "instructions": "Hinge forward until torso is nearly parallel to floor. Hold light dumbbells hanging down. With elbows slightly bent, raise arms out to sides squeezing rear delts, lower slowly.",
        "default_sets": 3,
        "default_reps": 15,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "12-15 reps",
        "common_mistakes": "Using heavy weights and jerking torso up, pulling with lats instead of rear deltoids.",
        "rest_seconds": 60,
        "youtube_id": "ttvfGg9d76c",
        "youtube_url": "https://www.youtube.com/watch?v=ttvfGg9d76c"
    },

    # ================= BICEPS =================
    {
        "name": "Barbell Bicep Curl",
        "category": "Biceps",
        "muscle_group": "Biceps Brachii (Short & Long Head), Brachialis",
        "equipment": "Barbell",
        "difficulty": "Beginner",
        "description": "Heavy mass-building curl loading both biceps heads with maximal mechanical tension across the sagittal plane.",
        "instructions": "Stand tall holding barbell with shoulder-width underhand grip. Pin elbows strictly to sides. Curl barbell upward contracting biceps, hold peak squeeze at chest height for 1s, lower over 2-3s.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Swinging hips back and forth, dragging elbows backward, letting wrists collapse backward under weight.",
        "rest_seconds": 60,
        "youtube_id": "ykJmrZ5v0Oo",
        "youtube_url": "https://www.youtube.com/watch?v=ykJmrZ5v0Oo"
    },
    {
        "name": "Incline Dumbbell Curl",
        "category": "Biceps",
        "muscle_group": "Biceps Brachii Long Head (Biceps Peak)",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Places the long head of the bicep under a deep passive stretch behind the torso for superior hypertrophy stimulus.",
        "instructions": "Set bench to 45-60 degrees. Lean back letting arms hang perpendicular to floor. Curl dumbbells upward keeping upper arms stationary behind torso, supinate wrists at top.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "10-12 reps",
        "common_mistakes": "Bringing upper arms forward during the curl, setting bench too low causing shoulder strain.",
        "rest_seconds": 60,
        "youtube_id": "soxrZlIl35U",
        "youtube_url": "https://www.youtube.com/watch?v=soxrZlIl35U"
    },
    {
        "name": "Hammer Curls",
        "category": "Biceps",
        "muscle_group": "Brachialis, Brachioradialis, Biceps Long Head",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Neutral-grip curl targeting the brachialis muscle underneath the bicep to push the upper arm peak higher and build forearm thickness.",
        "instructions": "Stand holding dumbbells with palms facing each other (neutral grip). Keeping elbows fixed, curl dumbbells up toward shoulders, pause, and lower slowly.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "10-15 reps",
        "common_mistakes": "Alternating with torso twisting, swinging dumbbells like kettlebells.",
        "rest_seconds": 60,
        "youtube_id": "zC3Ey1xQeaE",
        "youtube_url": "https://www.youtube.com/watch?v=zC3Ey1xQeaE"
    },
    {
        "name": "Cable Preacher Curl",
        "category": "Biceps",
        "muscle_group": "Biceps Brachii Short Head (Inner Bicep Thickness)",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "Locks the upper arm at a forward incline on preacher pad for strict short head bicep isolation with constant cable resistance.",
        "instructions": "Adjust preacher bench in front of low cable. Rest triceps fully on pad. Curl bar toward forehead, squeeze intensely at full elbow flexion, lower to a controlled stretch.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3 sets",
        "recommended_reps": "10-14 reps",
        "common_mistakes": "Hyperextending elbows dangerously at the bottom, lifting triceps off the preacher pad.",
        "rest_seconds": 60,
        "youtube_id": "fIWP-FRFNU0",
        "youtube_url": "https://www.youtube.com/watch?v=fIWP-FRFNU0"
    },

    # ================= TRICEPS =================
    {
        "name": "Tricep Pushdown (Cable Rope)",
        "category": "Triceps",
        "muscle_group": "Triceps Lateral Head, Medial Head (Horsehoe Shape)",
        "equipment": "Cable",
        "difficulty": "Beginner",
        "description": "The fundamental cable pushdown movement allowing wrists to flare out at bottom for complete lateral tricep contraction.",
        "instructions": "Grip rope attachment at high pulley. Pin elbows strictly against ribs. Push rope downward extending elbows, spread rope handles apart at bottom and flex triceps hard for 1s.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "10-15 reps",
        "common_mistakes": "Letting elbows flare forward and outward, leaning over weight and using chest/shoulders to push down.",
        "rest_seconds": 60,
        "youtube_id": "-xa-6cQaZKY",
        "youtube_url": "https://www.youtube.com/watch?v=-xa-6cQaZKY"
    },
    {
        "name": "Skull Crushers (Lying Triceps Extension)",
        "category": "Triceps",
        "muscle_group": "Triceps Long Head & Medial Head",
        "equipment": "Barbell",
        "difficulty": "Intermediate",
        "description": "Premier stretch-mediated hypertrophy builder for the meaty long head of the tricep which accounts for 60% of upper-arm mass.",
        "instructions": "Lie on flat bench holding EZ bar or barbell directly above chest. Keeping upper arms tilted slightly backward (~10 degrees toward head), bend elbows lowering bar to crown of head, extend back to start.",
        "default_sets": 3,
        "default_reps": 10,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "8-12 reps",
        "common_mistakes": "Letting elbows flare outwards, dropping the bar too fast toward forehead, moving upper arms forward and back.",
        "rest_seconds": 75,
        "youtube_id": "d_KZxkY_0cM",
        "youtube_url": "https://www.youtube.com/watch?v=d_KZxkY_0cM"
    },
    {
        "name": "Overhead Dumbbell Tricep Extension",
        "category": "Triceps",
        "muscle_group": "Triceps Brachii Long Head",
        "equipment": "Dumbbell",
        "difficulty": "Beginner",
        "description": "Overhead posture fully stretches the long head of the tricep across the shoulder joint for exceptional growth stimulation.",
        "instructions": "Sit or stand holding one dumbbell overhead with both hands cupping the top plate. Lower dumbbell behind head by bending elbows while keeping upper arms vertical, press back up.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "10-14 reps",
        "common_mistakes": "Arching lower back, letting elbows flare out excessively wide to sides.",
        "rest_seconds": 60,
        "youtube_id": "_dfqKX50ah8",
        "youtube_url": "https://www.youtube.com/watch?v=_dfqKX50ah8"
    },
    {
        "name": "Bench Tricep Dips",
        "category": "Triceps",
        "muscle_group": "Triceps Brachii, Anterior Deltoids",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Accessible bodyweight tricep burnout exercise targeting lockout extension and tricep density.",
        "instructions": "Place hands on bench behind hips, legs extended forward. Lower hips toward floor by bending elbows to 90 degrees, push through palms to full lockout.",
        "default_sets": 3,
        "default_reps": 15,
        "recommended_sets": "3 sets",
        "recommended_reps": "12-20 reps",
        "common_mistakes": "Shrugging shoulders into ears, letting hips drift too far away from bench (shoulder strain).",
        "rest_seconds": 60,
        "youtube_id": "0326dy_-CzM",
        "youtube_url": "https://www.youtube.com/watch?v=0326dy_-CzM"
    },

    # ================= LEGS =================
    {
        "name": "Barbell Back Squat",
        "category": "Legs",
        "muscle_group": "Quadriceps, Gluteus Maximus, Adductor Magnus, Erector Spinae",
        "equipment": "Barbell",
        "difficulty": "Advanced",
        "description": "The undisputed cornerstone of lower-body muscle development, triggering maximum systemic anabolic signaling and leg mass.",
        "instructions": "Rest barbell across upper traps. Unrack and step back. Stance shoulder-width with toes slightly turned out. Brace core 360 degrees. Sit hips back and down until thighs are parallel or below, drive upward through mid-foot.",
        "default_sets": 4,
        "default_reps": 8,
        "recommended_sets": "3-5 sets",
        "recommended_reps": "6-10 reps",
        "common_mistakes": "Knees caving inwards (valgus collapse), heels rising off floor, butt wink/lumbar rounding at bottom.",
        "rest_seconds": 120,
        "youtube_id": "bEv6CCg2BC8",
        "youtube_url": "https://www.youtube.com/watch?v=bEv6CCg2BC8"
    },
    {
        "name": "Leg Press",
        "category": "Legs",
        "muscle_group": "Quadriceps, Glutes, Hamstrings",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Heavy quad hypertrophy builder eliminating spinal compression and allowing athletes to train to true muscular failure.",
        "instructions": "Sit in machine with back and head flat against backrest. Place feet shoulder-width on platform. Release safety handles, lower sled until knees reach 90 degrees without lower back peeling up, press back up without locking knees.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "10-15 reps (Hypertrophy / Volume)",
        "common_mistakes": "Locking knees out violently at top, letting lower back round off pad at bottom, partial range of motion.",
        "rest_seconds": 90,
        "youtube_id": "IZxyjW7MPJQ",
        "youtube_url": "https://www.youtube.com/watch?v=IZxyjW7MPJQ"
    },
    {
        "name": "Lying Leg Curl",
        "category": "Legs",
        "muscle_group": "Hamstrings (Biceps Femoris, Semitendinosus, Semimembranosus)",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Premier knee-flexion hamstring isolation movement delivering targeted stretch and contraction for thick hamstring sweeps.",
        "instructions": "Lie face down on machine with leg pad resting against lower calves just below achilles. Keep hips firmly pressed into bench. Curl pad upward toward glutes, hold 1s peak squeeze, lower under 3s eccentric control.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "10-14 reps",
        "common_mistakes": "Arching lower back and lifting hips off the pad to heave the weight up, letting weights slam between reps.",
        "rest_seconds": 75,
        "youtube_id": "1Tq3QdYUuHs",
        "youtube_url": "https://www.youtube.com/watch?v=1Tq3QdYUuHs"
    },
    {
        "name": "Leg Extension",
        "category": "Legs",
        "muscle_group": "Quadriceps (Rectus Femoris, Vastus Lateralis, Vastus Medialis)",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Direct open-chain quadriceps isolation exercise emphasizing the rectus femoris and tear-drop (VMO) definition.",
        "instructions": "Sit back securely against backrest with knees aligned with machine pivot axis. Hook shins beneath roller pad. Extend legs upward until fully straight, flex quads hard at the apex, lower smoothly.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "12-15 reps",
        "common_mistakes": "Kicking the weight up with jerky momentum, setting knee alignment forward or behind machine pivot.",
        "rest_seconds": 60,
        "youtube_id": "YyvSfV-IZQ4",
        "youtube_url": "https://www.youtube.com/watch?v=YyvSfV-IZQ4"
    },
    {
        "name": "Walking Dumbbell Lunges",
        "category": "Legs",
        "muscle_group": "Gluteus Maximus, Quadriceps, Adductors, Core Stabilizers",
        "equipment": "Dumbbell",
        "difficulty": "Intermediate",
        "description": "Unilateral dynamic movement developing single-leg functional balance, glute growth, and athletic hip stability.",
        "instructions": "Hold dumbbells at sides. Step forward into lunge until trailing knee gently taps floor. Drive through front heel to step forward into next lunge, maintaining upright posture.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3 sets",
        "recommended_reps": "10-14 steps per leg",
        "common_mistakes": "Banging back knee hard onto floor, letting front knee track inward, leaning excessively forward.",
        "rest_seconds": 90,
        "youtube_id": "D7KaRcUTQeE",
        "youtube_url": "https://www.youtube.com/watch?v=D7KaRcUTQeE"
    },
    {
        "name": "Standing Calf Raise",
        "category": "Legs",
        "muscle_group": "Gastrocnemius, Soleus (Lower Leg Mass)",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Crucial standing calf isolation with extended knee joint to fully engage the double-headed gastrocnemius diamond.",
        "instructions": "Stand on platform with balls of feet, shoulders under pads. Lower heels deep below platform level for a full 2-second stretch. Drive up onto big toes and hold peak squeeze for 1 second.",
        "default_sets": 4,
        "default_reps": 15,
        "recommended_sets": "3-5 sets",
        "recommended_reps": "12-18 reps (Pause at stretch & peak)",
        "common_mistakes": "Bouncing up and down utilizing achilles tendon elastic recoil rather than muscular work, cutting range of motion.",
        "rest_seconds": 60,
        "youtube_id": "N488kG_5pL4",
        "youtube_url": "https://www.youtube.com/watch?v=N488kG_5pL4"
    },
    {
        "name": "Nordic Hamstring Curl",
        "category": "Legs",
        "muscle_group": "Hamstrings (Eccentric Overload), Calves",
        "equipment": "Bodyweight",
        "difficulty": "Advanced",
        "description": "High-intensity bodyweight eccentric hamstring exercise renowned for reducing injury risk and generating deep mechanical tension.",
        "instructions": "Kneel with ankles anchored firmly. Keep hips extended in a straight line with torso. Lower body forward as slowly as possible using hamstrings to resist gravity, catch with hands, push up.",
        "default_sets": 3,
        "default_reps": 6,
        "recommended_sets": "3 sets",
        "recommended_reps": "5-8 reps",
        "common_mistakes": "Bending at the hips (losing straight body alignment), dropping forward without resisting.",
        "rest_seconds": 90,
        "youtube_id": None,
        "youtube_url": None
    },

    # ================= CORE & ABS =================
    {
        "name": "Abdominal Plank",
        "category": "Core",
        "muscle_group": "Transverse Abdominis, Rectus Abdominis, Obliques, Serratus Anterior",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Isometric anti-extension core foundation bracing the entire anterior abdominal wall and stabilizing spinal alignment.",
        "instructions": "Rest on forearms and toes. Keep elbows directly under shoulders. Squeeze glutes and tuck pelvis slightly (posterior pelvic tilt). Draw belly button inward, maintaining a rigid straight line for time.",
        "default_sets": 3,
        "default_reps": 45,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "45-60 seconds hold",
        "common_mistakes": "Sagging lower back, arching hips into a triangle pike, holding breath.",
        "rest_seconds": 60,
        "youtube_id": "TvxNkmjdhMM",
        "youtube_url": "https://www.youtube.com/watch?v=TvxNkmjdhMM"
    },
    {
        "name": "Cable Woodchoppers",
        "category": "Core",
        "muscle_group": "Internal & External Obliques, Transverse Abdominis",
        "equipment": "Cable",
        "difficulty": "Intermediate",
        "description": "Dynamic rotational cable exercise for strengthening the torso against rotational forces and carving oblique striations.",
        "instructions": "Set pulley at shoulder height. Stand sideways to machine holding handle with both hands. Rotate torso across body keeping arms straight and pivoting on back foot, control return.",
        "default_sets": 3,
        "default_reps": 15,
        "recommended_sets": "3 sets",
        "recommended_reps": "12-15 reps per side",
        "common_mistakes": "Using arms to pull instead of turning from the core, not pivoting back foot.",
        "rest_seconds": 60,
        "youtube_id": "pZapR_Ldgm4",
        "youtube_url": "https://www.youtube.com/watch?v=pZapR_Ldgm4"
    },
    {
        "name": "Russian Twists",
        "category": "Core",
        "muscle_group": "Obliques, Rectus Abdominis",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Seated rotational isometric core developer focusing on oblique contraction and transverse abdominal tension.",
        "instructions": "Sit on floor, lean back to 45 degrees, elevate feet off floor. Clasp hands or hold weight plate, rotate torso from side to side tapping floor beside hips under controlled tempo.",
        "default_sets": 3,
        "default_reps": 20,
        "recommended_sets": "3 sets",
        "recommended_reps": "16-24 total reps",
        "common_mistakes": "Moving only arms instead of twisting ribcage, rounding lower back violently.",
        "rest_seconds": 60,
        "youtube_id": "wkD8rjkodUI",
        "youtube_url": "https://www.youtube.com/watch?v=wkD8rjkodUI"
    },
    {
        "name": "Hanging Leg Raise",
        "category": "Abs",
        "muscle_group": "Lower Rectus Abdominis, Hip Flexors, Grip",
        "equipment": "Bodyweight",
        "difficulty": "Intermediate",
        "description": "Premier lower-abdominal flexion exercise creating defined six-pack brick separation and core control.",
        "instructions": "Hang from pull-up bar. Without swinging torso, roll pelvis backward and raise straight legs (or knees) upward until thighs hit horizontal or touch chest, lower under 2s control.",
        "default_sets": 3,
        "default_reps": 12,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "10-15 reps",
        "common_mistakes": "Swinging legs like a pendulum, lifting legs using only hip flexors without curling the pelvis forward.",
        "rest_seconds": 60,
        "youtube_id": "hdng3Nm1x_E",
        "youtube_url": "https://www.youtube.com/watch?v=hdng3Nm1x_E"
    },
    {
        "name": "Abdominal Crunch Machine",
        "category": "Abs",
        "muscle_group": "Upper & Mid Rectus Abdominis (Six-Pack Peak)",
        "equipment": "Machine",
        "difficulty": "Beginner",
        "description": "Weighted mechanical flexion exercise allowing progressive overload for thick, deep abdominal definition.",
        "instructions": "Sit in machine with chest pad against upper torso, feet hooked under rollers. Flex spine forward curling ribcage toward pelvis, hold peak contraction for 1 second, resist return.",
        "default_sets": 3,
        "default_reps": 15,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "12-15 reps",
        "common_mistakes": "Using arms or neck to push weight forward, not flexing the spine (hip hinging instead).",
        "rest_seconds": 60,
        "youtube_id": "29J_sR6O6Y8",
        "youtube_url": "https://www.youtube.com/watch?v=29J_sR6O6Y8"
    },
    {
        "name": "Cable Kneeling Crunch",
        "category": "Abs",
        "muscle_group": "Rectus Abdominis, Upper Abdominals",
        "equipment": "Cable",
        "difficulty": "Intermediate",
        "description": "Continuous tension loaded spinal flexion for packing direct muscle mass onto the abdominal wall.",
        "instructions": "Kneel beneath high pulley holding rope attachment at ears. Hinge and curl spine down, bringing elbows toward thighs by crunching abs hard, return with control.",
        "default_sets": 3,
        "default_reps": 15,
        "recommended_sets": "3-4 sets",
        "recommended_reps": "12-15 reps",
        "common_mistakes": "Sitting hips back onto heels like a hip hinge instead of curling the thoracic and lumbar spine.",
        "rest_seconds": 60,
        "youtube_id": "2fORO70ffPA",
        "youtube_url": "https://www.youtube.com/watch?v=2fORO70ffPA"
    },
    {
        "name": "Decline Bench Sit-Ups",
        "category": "Abs",
        "muscle_group": "Rectus Abdominis, Hip Flexors",
        "equipment": "Bodyweight",
        "difficulty": "Beginner",
        "description": "Full-range abdominal builder intensifying gravitational torque on the rectus abdominis.",
        "instructions": "Hook feet on decline bench. Cross hands over chest, lower spine back until almost parallel to floor, then curl torso up contracting abdominals.",
        "default_sets": 3,
        "default_reps": 15,
        "recommended_sets": "3 sets",
        "recommended_reps": "12-15 reps",
        "common_mistakes": "Pulling on neck with hands, hyperextending lower back at the bottom of the decline.",
        "rest_seconds": 60,
        "youtube_id": "5_4U0u8F1lE",
        "youtube_url": "https://www.youtube.com/watch?v=5_4U0u8F1lE"
    }
]

def seed_exercise_catalog(conn):
    """Inserts or updates all exercises in the comprehensive catalog with YouTube references."""
    cursor = conn.cursor()
    for ex in EXERCISE_CATALOG:
        cursor.execute("SELECT id FROM exercises WHERE name = ?", (ex['name'],))
        existing = cursor.fetchone()
        if existing:
            cursor.execute("""
                UPDATE exercises SET
                    category = ?,
                    muscle_group = ?,
                    equipment = ?,
                    difficulty = ?,
                    description = ?,
                    instructions = ?,
                    default_sets = ?,
                    default_reps = ?,
                    recommended_sets = ?,
                    recommended_reps = ?,
                    common_mistakes = ?,
                    rest_seconds = ?,
                    youtube_id = ?,
                    youtube_url = ?
                WHERE id = ?
            """, (
                ex['category'], ex['muscle_group'], ex['equipment'], ex['difficulty'],
                ex['description'], ex['instructions'], ex['default_sets'], ex['default_reps'],
                ex['recommended_sets'], ex['recommended_reps'], ex['common_mistakes'],
                ex['rest_seconds'], ex.get('youtube_id'), ex.get('youtube_url'), existing[0]
            ))
        else:
            cursor.execute("""
                INSERT INTO exercises (
                    name, category, muscle_group, equipment, difficulty,
                    description, instructions, default_sets, default_reps,
                    recommended_sets, recommended_reps, common_mistakes, rest_seconds,
                    youtube_id, youtube_url
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                ex['name'], ex['category'], ex['muscle_group'], ex['equipment'], ex['difficulty'],
                ex['description'], ex['instructions'], ex['default_sets'], ex['default_reps'],
                ex['recommended_sets'], ex['recommended_reps'], ex['common_mistakes'],
                ex['rest_seconds'], ex.get('youtube_id'), ex.get('youtube_url')
            ))
    conn.commit()
