-- Muscle Building & Fitness Tracking Database Schema (PostgreSQL)

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    age INTEGER DEFAULT 26,
    gender TEXT DEFAULT 'Male',
    height_cm DOUBLE PRECISION DEFAULT 180.0,
    weight_kg DOUBLE PRECISION DEFAULT 78.5,
    experience_level TEXT DEFAULT 'Intermediate (1-3 Years)',
    fitness_goal TEXT DEFAULT 'Muscle Hypertrophy & Strength',
    training_days_per_week INTEGER DEFAULT 4,
    available_equipment TEXT DEFAULT 'Full Commercial Gym',
    dietary_preference TEXT DEFAULT 'High Protein Omnivore',
    target_weight_kg DOUBLE PRECISION DEFAULT 82.0,
    daily_calorie_target INTEGER DEFAULT 2850,
    daily_protein_target INTEGER DEFAULT 185,
    daily_carbs_target INTEGER DEFAULT 320,
    daily_fats_target INTEGER DEFAULT 75,
    google_id TEXT UNIQUE,
    profile_picture TEXT,
    auth_provider TEXT DEFAULT 'local',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_google_id ON users(google_id) WHERE google_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    muscle_group TEXT NOT NULL,
    equipment TEXT NOT NULL,
    difficulty TEXT NOT NULL,
    description TEXT,
    instructions TEXT,
    default_sets INTEGER DEFAULT 3,
    default_reps INTEGER DEFAULT 10,
    recommended_sets TEXT DEFAULT '3-4 sets',
    recommended_reps TEXT DEFAULT '8-12 reps',
    common_mistakes TEXT,
    rest_seconds INTEGER DEFAULT 90,
    youtube_id TEXT,
    youtube_url TEXT
);

CREATE TABLE IF NOT EXISTS workout_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    fitness_goal TEXT NOT NULL,
    experience_level TEXT NOT NULL,
    days_per_week INTEGER NOT NULL,
    available_equipment TEXT NOT NULL,
    target_muscle_group TEXT DEFAULT 'All',
    is_default INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workout_plan_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id INTEGER NOT NULL REFERENCES workout_plans(id) ON DELETE CASCADE,
    day_number INTEGER NOT NULL,
    day_title TEXT NOT NULL,
    focus_category TEXT NOT NULL,
    is_rest_day INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS workout_plan_exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_day_id INTEGER NOT NULL REFERENCES workout_plan_days(id) ON DELETE CASCADE,
    exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    sets INTEGER DEFAULT 3,
    reps INTEGER DEFAULT 10,
    rest_seconds INTEGER DEFAULT 90,
    order_idx INTEGER DEFAULT 1,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS user_active_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id INTEGER NOT NULL REFERENCES workout_plans(id) ON DELETE CASCADE,
    started_at DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS workouts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    date DATE NOT NULL,
    duration_minutes INTEGER DEFAULT 60,
    total_volume_kg DOUBLE PRECISION DEFAULT 0,
    intensity_rating INTEGER DEFAULT 8,
    status TEXT DEFAULT 'completed',
    target_muscle_group TEXT DEFAULT 'General',
    completion_rate INTEGER DEFAULT 100,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_workouts_user_date ON workouts (user_id, date);

CREATE TABLE IF NOT EXISTS workout_exercises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id INTEGER NOT NULL REFERENCES workouts(id) ON DELETE CASCADE,
    exercise_id INTEGER NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight_kg DOUBLE PRECISION NOT NULL,
    rest_seconds INTEGER DEFAULT 90,
    completed INTEGER DEFAULT 1,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS food_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL,
    serving_size TEXT NOT NULL,
    serving_unit TEXT NOT NULL,
    calories INTEGER NOT NULL,
    protein_g DOUBLE PRECISION DEFAULT 0,
    carbs_g DOUBLE PRECISION DEFAULT 0,
    fats_g DOUBLE PRECISION DEFAULT 0,
    is_muscle_building INTEGER DEFAULT 1,
    description TEXT
);

CREATE TABLE IF NOT EXISTS nutrition_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    meal_type TEXT NOT NULL,
    food_name TEXT NOT NULL,
    quantity DOUBLE PRECISION DEFAULT 1.0,
    serving_unit TEXT DEFAULT 'serving',
    calories INTEGER NOT NULL,
    protein_g DOUBLE PRECISION DEFAULT 0,
    carbs_g DOUBLE PRECISION DEFAULT 0,
    fats_g DOUBLE PRECISION DEFAULT 0,
    logged_via TEXT DEFAULT 'manual',
    is_estimate INTEGER DEFAULT 0,
    image_path TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_nutrition_user_date ON nutrition_logs (user_id, date);

CREATE TABLE IF NOT EXISTS progress_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    weight_kg DOUBLE PRECISION NOT NULL,
    body_fat_pct DOUBLE PRECISION,
    chest_cm DOUBLE PRECISION,
    arms_cm DOUBLE PRECISION,
    waist_cm DOUBLE PRECISION,
    thighs_cm DOUBLE PRECISION,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_progress_user_date ON progress_logs (user_id, date);

CREATE TABLE IF NOT EXISTS ai_chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_daily_schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    workout_id INTEGER,
    workout_title TEXT,
    target_muscle_group TEXT DEFAULT 'General',
    duration_minutes INTEGER DEFAULT 60,
    exercise_id INTEGER NOT NULL REFERENCES exercises(id),
    sets INTEGER NOT NULL DEFAULT 3,
    reps INTEGER NOT NULL DEFAULT 10,
    rest_time INTEGER NOT NULL DEFAULT 90,
    exercise_order INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_daily_schedules ON user_daily_schedules (user_id, date);
